/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppUniverseRouteImport } from './routes/app.universe'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as CheckoutServiceIdRouteImport } from './routes/checkout.$serviceId'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderCreateServiceRouteImport } from './routes/provider.create-service'
import { Route as ProviderLogsRouteImport } from './routes/provider.logs'
import { Route as AppAdminVerificationRouteImport } from './routes/app.admin.verification'
import { Route as AppBuyerContractsRouteImport } from './routes/app.buyer.contracts'
import { Route as AppBuyerIntakeRouteImport } from './routes/app.buyer.intake'
import { Route as AppBuyerMatchesRouteImport } from './routes/app.buyer.matches'
import { Route as AppBuyerPaymentsRouteImport } from './routes/app.buyer.payments'
import { Route as AppBuyerProposalsRouteImport } from './routes/app.buyer.proposals'
import { Route as AppBuyerRequestsRouteImport } from './routes/app.buyer.requests'
import { Route as AppBuyerReviewsRouteImport } from './routes/app.buyer.reviews'
import { Route as AppBuyerSavedRouteImport } from './routes/app.buyer.saved'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/app.opportunities.index'
import { Route as AppOpportunitiesIdRouteImport } from './routes/app.opportunities.$id'
import { Route as AppOrganizationOverviewRouteImport } from './routes/app.organization.overview'
import { Route as AppOrganizationPodsRouteImport } from './routes/app.organization.pods'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app.organizations.index'
import { Route as AppOrganizationsSlugRouteImport } from './routes/app.organizations.$slug'
import { Route as AppProfessionalsIndexRouteImport } from './routes/app.professionals.index'
import { Route as AppProfessionalsHandleRouteImport } from './routes/app.professionals.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUniverseRoute = AppUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutServiceIdRoute = CheckoutServiceIdRouteImport.update({
  id: '/checkout/$serviceId',
  path: '/checkout/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderCreateServiceRoute = ProviderCreateServiceRouteImport.update({
  id: '/create-service',
  path: '/create-service',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderLogsRoute = ProviderLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProviderRoute,
} as any)
const AppAdminVerificationRoute = AppAdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppBuyerContractsRoute = AppBuyerContractsRouteImport.update({
  id: '/buyer/contracts',
  path: '/buyer/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerIntakeRoute = AppBuyerIntakeRouteImport.update({
  id: '/buyer/intake',
  path: '/buyer/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerMatchesRoute = AppBuyerMatchesRouteImport.update({
  id: '/buyer/matches',
  path: '/buyer/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerPaymentsRoute = AppBuyerPaymentsRouteImport.update({
  id: '/buyer/payments',
  path: '/buyer/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerProposalsRoute = AppBuyerProposalsRouteImport.update({
  id: '/buyer/proposals',
  path: '/buyer/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerRequestsRoute = AppBuyerRequestsRouteImport.update({
  id: '/buyer/requests',
  path: '/buyer/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerReviewsRoute = AppBuyerReviewsRouteImport.update({
  id: '/buyer/reviews',
  path: '/buyer/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerSavedRoute = AppBuyerSavedRouteImport.update({
  id: '/buyer/saved',
  path: '/buyer/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationOverviewRoute = AppOrganizationOverviewRouteImport.update({
  id: '/organization/overview',
  path: '/organization/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationPodsRoute = AppOrganizationPodsRouteImport.update({
  id: '/organization/pods',
  path: '/organization/pods',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsSlugRoute = AppOrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessionalsIndexRoute = AppProfessionalsIndexRouteImport.update({
  id: '/professionals/',
  path: '/professionals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessionalsHandleRoute = AppProfessionalsHandleRouteImport.update({
  id: '/professionals/$handle',
  path: '/professionals/$handle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/learning': typeof AppLearningRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/universe': typeof AppUniverseRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/$serviceId': typeof CheckoutServiceIdRoute
  '/provider/create-service': typeof ProviderCreateServiceRoute
  '/provider/logs': typeof ProviderLogsRoute
  '/app/': typeof AppIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/buyer/contracts': typeof AppBuyerContractsRoute
  '/app/buyer/intake': typeof AppBuyerIntakeRoute
  '/app/buyer/matches': typeof AppBuyerMatchesRoute
  '/app/buyer/payments': typeof AppBuyerPaymentsRoute
  '/app/buyer/proposals': typeof AppBuyerProposalsRoute
  '/app/buyer/requests': typeof AppBuyerRequestsRoute
  '/app/buyer/reviews': typeof AppBuyerReviewsRoute
  '/app/buyer/saved': typeof AppBuyerSavedRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/organization/overview': typeof AppOrganizationOverviewRoute
  '/app/organization/pods': typeof AppOrganizationPodsRoute
  '/app/organizations/$slug': typeof AppOrganizationsSlugRoute
  '/app/professionals/$handle': typeof AppProfessionalsHandleRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/professionals/': typeof AppProfessionalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/learning': typeof AppLearningRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/universe': typeof AppUniverseRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/$serviceId': typeof CheckoutServiceIdRoute
  '/provider/create-service': typeof ProviderCreateServiceRoute
  '/provider/logs': typeof ProviderLogsRoute
  '/app': typeof AppIndexRoute
  '/provider': typeof ProviderIndexRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/buyer/contracts': typeof AppBuyerContractsRoute
  '/app/buyer/intake': typeof AppBuyerIntakeRoute
  '/app/buyer/matches': typeof AppBuyerMatchesRoute
  '/app/buyer/payments': typeof AppBuyerPaymentsRoute
  '/app/buyer/proposals': typeof AppBuyerProposalsRoute
  '/app/buyer/requests': typeof AppBuyerRequestsRoute
  '/app/buyer/reviews': typeof AppBuyerReviewsRoute
  '/app/buyer/saved': typeof AppBuyerSavedRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/organization/overview': typeof AppOrganizationOverviewRoute
  '/app/organization/pods': typeof AppOrganizationPodsRoute
  '/app/organizations/$slug': typeof AppOrganizationsSlugRoute
  '/app/professionals/$handle': typeof AppProfessionalsHandleRoute
  '/app/opportunities': typeof AppOpportunitiesIndexRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/professionals': typeof AppProfessionalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/learning': typeof AppLearningRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/universe': typeof AppUniverseRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/$serviceId': typeof CheckoutServiceIdRoute
  '/provider/create-service': typeof ProviderCreateServiceRoute
  '/provider/logs': typeof ProviderLogsRoute
  '/app/': typeof AppIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/buyer/contracts': typeof AppBuyerContractsRoute
  '/app/buyer/intake': typeof AppBuyerIntakeRoute
  '/app/buyer/matches': typeof AppBuyerMatchesRoute
  '/app/buyer/payments': typeof AppBuyerPaymentsRoute
  '/app/buyer/proposals': typeof AppBuyerProposalsRoute
  '/app/buyer/requests': typeof AppBuyerRequestsRoute
  '/app/buyer/reviews': typeof AppBuyerReviewsRoute
  '/app/buyer/saved': typeof AppBuyerSavedRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/organization/overview': typeof AppOrganizationOverviewRoute
  '/app/organization/pods': typeof AppOrganizationPodsRoute
  '/app/organizations/$slug': typeof AppOrganizationsSlugRoute
  '/app/professionals/$handle': typeof AppProfessionalsHandleRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/professionals/': typeof AppProfessionalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/docs'
    | '/manifesto'
    | '/pricing'
    | '/privacy'
    | '/provider'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assets'
    | '/app/community'
    | '/app/learning'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/universe'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/$serviceId'
    | '/provider/create-service'
    | '/provider/logs'
    | '/app/'
    | '/provider/'
    | '/app/admin/verification'
    | '/app/buyer/contracts'
    | '/app/buyer/intake'
    | '/app/buyer/matches'
    | '/app/buyer/payments'
    | '/app/buyer/proposals'
    | '/app/buyer/requests'
    | '/app/buyer/reviews'
    | '/app/buyer/saved'
    | '/app/opportunities/$id'
    | '/app/organization/overview'
    | '/app/organization/pods'
    | '/app/organizations/$slug'
    | '/app/professionals/$handle'
    | '/app/opportunities/'
    | '/app/organizations/'
    | '/app/professionals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/manifesto'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assets'
    | '/app/community'
    | '/app/learning'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/universe'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/$serviceId'
    | '/provider/create-service'
    | '/provider/logs'
    | '/app'
    | '/provider'
    | '/app/admin/verification'
    | '/app/buyer/contracts'
    | '/app/buyer/intake'
    | '/app/buyer/matches'
    | '/app/buyer/payments'
    | '/app/buyer/proposals'
    | '/app/buyer/requests'
    | '/app/buyer/reviews'
    | '/app/buyer/saved'
    | '/app/opportunities/$id'
    | '/app/organization/overview'
    | '/app/organization/pods'
    | '/app/organizations/$slug'
    | '/app/professionals/$handle'
    | '/app/opportunities'
    | '/app/organizations'
    | '/app/professionals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/docs'
    | '/manifesto'
    | '/pricing'
    | '/privacy'
    | '/provider'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assets'
    | '/app/community'
    | '/app/learning'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/universe'
    | '/auth/login'
    | '/auth/signup'
    | '/checkout/$serviceId'
    | '/provider/create-service'
    | '/provider/logs'
    | '/app/'
    | '/provider/'
    | '/app/admin/verification'
    | '/app/buyer/contracts'
    | '/app/buyer/intake'
    | '/app/buyer/matches'
    | '/app/buyer/payments'
    | '/app/buyer/proposals'
    | '/app/buyer/requests'
    | '/app/buyer/reviews'
    | '/app/buyer/saved'
    | '/app/opportunities/$id'
    | '/app/organization/overview'
    | '/app/organization/pods'
    | '/app/organizations/$slug'
    | '/app/professionals/$handle'
    | '/app/opportunities/'
    | '/app/organizations/'
    | '/app/professionals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  ManifestoRoute: typeof ManifestoRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CheckoutServiceIdRoute: typeof CheckoutServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/universe': {
      id: '/app/universe'
      path: '/universe'
      fullPath: '/app/universe'
      preLoaderRoute: typeof AppUniverseRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$serviceId': {
      id: '/checkout/$serviceId'
      path: '/checkout/$serviceId'
      fullPath: '/checkout/$serviceId'
      preLoaderRoute: typeof CheckoutServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/create-service': {
      id: '/provider/create-service'
      path: '/create-service'
      fullPath: '/provider/create-service'
      preLoaderRoute: typeof ProviderCreateServiceRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/logs': {
      id: '/provider/logs'
      path: '/logs'
      fullPath: '/provider/logs'
      preLoaderRoute: typeof ProviderLogsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/app/admin/verification': {
      id: '/app/admin/verification'
      path: '/verification'
      fullPath: '/app/admin/verification'
      preLoaderRoute: typeof AppAdminVerificationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/buyer/contracts': {
      id: '/app/buyer/contracts'
      path: '/buyer/contracts'
      fullPath: '/app/buyer/contracts'
      preLoaderRoute: typeof AppBuyerContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/intake': {
      id: '/app/buyer/intake'
      path: '/buyer/intake'
      fullPath: '/app/buyer/intake'
      preLoaderRoute: typeof AppBuyerIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/matches': {
      id: '/app/buyer/matches'
      path: '/buyer/matches'
      fullPath: '/app/buyer/matches'
      preLoaderRoute: typeof AppBuyerMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/payments': {
      id: '/app/buyer/payments'
      path: '/buyer/payments'
      fullPath: '/app/buyer/payments'
      preLoaderRoute: typeof AppBuyerPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/proposals': {
      id: '/app/buyer/proposals'
      path: '/buyer/proposals'
      fullPath: '/app/buyer/proposals'
      preLoaderRoute: typeof AppBuyerProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/requests': {
      id: '/app/buyer/requests'
      path: '/buyer/requests'
      fullPath: '/app/buyer/requests'
      preLoaderRoute: typeof AppBuyerRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/reviews': {
      id: '/app/buyer/reviews'
      path: '/buyer/reviews'
      fullPath: '/app/buyer/reviews'
      preLoaderRoute: typeof AppBuyerReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer/saved': {
      id: '/app/buyer/saved'
      path: '/buyer/saved'
      fullPath: '/app/buyer/saved'
      preLoaderRoute: typeof AppBuyerSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities/': {
      id: '/app/opportunities/'
      path: '/opportunities'
      fullPath: '/app/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities/$id': {
      id: '/app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/app/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization/overview': {
      id: '/app/organization/overview'
      path: '/organization/overview'
      fullPath: '/app/organization/overview'
      preLoaderRoute: typeof AppOrganizationOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization/pods': {
      id: '/app/organization/pods'
      path: '/organization/pods'
      fullPath: '/app/organization/pods'
      preLoaderRoute: typeof AppOrganizationPodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug': {
      id: '/app/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/app/organizations/$slug'
      preLoaderRoute: typeof AppOrganizationsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professionals/': {
      id: '/app/professionals/'
      path: '/professionals'
      fullPath: '/app/professionals/'
      preLoaderRoute: typeof AppProfessionalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professionals/$handle': {
      id: '/app/professionals/$handle'
      path: '/professionals/$handle'
      fullPath: '/app/professionals/$handle'
      preLoaderRoute: typeof AppProfessionalsHandleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminVerificationRoute: typeof AppAdminVerificationRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminVerificationRoute: AppAdminVerificationRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUniverseRoute: typeof AppUniverseRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBuyerContractsRoute: typeof AppBuyerContractsRoute
  AppBuyerIntakeRoute: typeof AppBuyerIntakeRoute
  AppBuyerMatchesRoute: typeof AppBuyerMatchesRoute
  AppBuyerPaymentsRoute: typeof AppBuyerPaymentsRoute
  AppBuyerProposalsRoute: typeof AppBuyerProposalsRoute
  AppBuyerRequestsRoute: typeof AppBuyerRequestsRoute
  AppBuyerReviewsRoute: typeof AppBuyerReviewsRoute
  AppBuyerSavedRoute: typeof AppBuyerSavedRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
  AppOrganizationOverviewRoute: typeof AppOrganizationOverviewRoute
  AppOrganizationPodsRoute: typeof AppOrganizationPodsRoute
  AppOrganizationsSlugRoute: typeof AppOrganizationsSlugRoute
  AppProfessionalsHandleRoute: typeof AppProfessionalsHandleRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppProfessionalsIndexRoute: typeof AppProfessionalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppLearningRoute: AppLearningRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUniverseRoute: AppUniverseRoute,
  AppIndexRoute: AppIndexRoute,
  AppBuyerContractsRoute: AppBuyerContractsRoute,
  AppBuyerIntakeRoute: AppBuyerIntakeRoute,
  AppBuyerMatchesRoute: AppBuyerMatchesRoute,
  AppBuyerPaymentsRoute: AppBuyerPaymentsRoute,
  AppBuyerProposalsRoute: AppBuyerProposalsRoute,
  AppBuyerRequestsRoute: AppBuyerRequestsRoute,
  AppBuyerReviewsRoute: AppBuyerReviewsRoute,
  AppBuyerSavedRoute: AppBuyerSavedRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
  AppOrganizationOverviewRoute: AppOrganizationOverviewRoute,
  AppOrganizationPodsRoute: AppOrganizationPodsRoute,
  AppOrganizationsSlugRoute: AppOrganizationsSlugRoute,
  AppProfessionalsHandleRoute: AppProfessionalsHandleRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppProfessionalsIndexRoute: AppProfessionalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProviderRouteChildren {
  ProviderCreateServiceRoute: typeof ProviderCreateServiceRoute
  ProviderLogsRoute: typeof ProviderLogsRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderCreateServiceRoute: ProviderCreateServiceRoute,
  ProviderLogsRoute: ProviderLogsRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  ManifestoRoute: ManifestoRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProviderRoute: ProviderRouteWithChildren,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CheckoutServiceIdRoute: CheckoutServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
